In [13]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_digits

digits = load_digits()

In [14]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [32]:
from sklearn.model_selection import train_test_split
X = digits.data
y = digits.target
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

### Evaluating different models and their scores

In [33]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9694444444444444

In [34]:
lir = LinearRegression()
lir.fit(X_train, y_train)
lir.score(X_test, y_test)

0.619859281250078

In [35]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9888888888888889

In [36]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test,y_test)

0.9777777777777777

In [45]:
# Now we are going to select the Kfold method
from sklearn.model_selection import KFold
kf  = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [46]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,10]):
    print(train_index, test_index)
    
# This will divide the data into multiple train test splits and feed that data to model for better performance

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [47]:
def getscore(model, X_train, X_test, y_train,y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

# This is a function for easily getting the score from all models one by one

In [48]:
# Implementation of the above function
getscore(svm, X_train, X_test, y_train, y_test)

0.9888888888888889

In [56]:
from sklearn.model_selection import cross_val_score

In [57]:
# For Logistic Regression
cross_val_score(lr, X,y, cv=3)

array([0.91986644, 0.94156928, 0.91652755])

In [59]:
# For Linear Regression
cross_val_score(lir, X,y, cv=3)

array([0.52105031, 0.56814242, 0.41943985])

In [60]:
# For Support Vector Machines
cross_val_score(svm, X,y,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [61]:
cross_val_score(rf, X,y,cv=3)

array([0.94323873, 0.95826377, 0.94156928])